"""
src/metrics.py — Prometheus Metrics instrumentation for K8s Copilot.

CONCEPT: OBSERVABILITY & PROMETHEUS METRICS
═══════════════════════════════════════════
In a production microservice or agentic pipeline, you cannot rely solely on terminal logs.
Prometheus is the CNCF standard monitoring system in Kubernetes.

Prometheus works via a "Pull / Scrape" model:
  1. Your application exposes an HTTP endpoint (usually GET /metrics).
  2. The Prometheus server periodically scrapes (polls) this endpoint (e.g. every 15s).
  3. Prometheus stores the time-series data and evaluates Alertmanager rules.
  4. Dashboards like Grafana query Prometheus to display real-time visual graphs.

CORE METRIC TYPES EXPLAINED:
  1. Counter: A cumulative metric that ONLY increases (or resets to zero on restart).
     Use for: Total number of requests, total errors, total investigations.
     Example: `k8s_copilot_investigations_total{status="completed"}`

  2. Histogram: Samples observations (usually request durations or scores) and counts
     them in configurable buckets. It also provides a sum of all observed values.
     Use for: Request latency, confidence score distributions, loop iteration counts.
     Example: `k8s_copilot_investigation_duration_seconds_bucket{le="10.0"}`

  3. Gauge: A metric that can go up AND down (e.g., current active threads, memory usage).

INTERVIEW TALKING POINT:
  "I instrumented the agentic supervisor with Prometheus metrics tracking investigation duration,
  synthesis confidence distributions, and LLM call counts per node. The `/metrics` endpoint is
  scraped by Prometheus and stays unauthenticated so standard cluster scrapers can access it
  without complex auth handshakes."
"""

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from fastapi import Response

# ── Metric 1: Total Investigations Counter ───────────────────────────────────
# Tracks total number of investigations started/finished, labeled by status.
# Labels allow Prometheus/Grafana to filter or group by status:
# sum(rate(k8s_copilot_investigations_total[5m])) by (status)
INVESTIGATIONS_TOTAL = Counter(
    "k8s_copilot_investigations_total",
    "Total number of Kubernetes alert investigations processed.",
    ["status"],  # Label dimensions: "paused_for_review", "completed", "failed"
)

# ── Metric 2: Investigation Duration Histogram ───────────────────────────────
# Measures how many seconds an investigation takes to run through graph nodes.
# Buckets are defined in seconds from 1s to 60s.
INVESTIGATION_DURATION_SECONDS = Histogram(
    "k8s_copilot_investigation_duration_seconds",
    "Duration of an investigation run through the supervisor graph in seconds.",
    buckets=[1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0],
)

# ── Metric 3: Synthesis Confidence Score Histogram ───────────────────────────
# Tracks the distribution of confidence scores (0.0 to 1.0) produced by the synthesizer.
# If you see a spike in the lower buckets (<0.5), it means the agent is struggling
# to identify root causes with current evidence, signalling potential prompt/tool degradation.
SYNTHESIS_CONFIDENCE = Histogram(
    "k8s_copilot_synthesis_confidence_score",
    "Distribution of confidence scores generated by the synthesis node (0.0 to 1.0).",
    buckets=[0.2, 0.4, 0.6, 0.75, 0.85, 0.95, 1.0],
)

# ── Metric 4: Supervisor Iteration Loops Histogram ───────────────────────────
# Tracks how many retry loops were needed before completing or stopping.
INVESTIGATION_ITERATIONS = Histogram(
    "k8s_copilot_investigation_iterations_total",
    "Number of loop iterations executed during an investigation before reaching a conclusion.",
    buckets=[1, 2, 3, 4, 5],
)

# ── Metric 5: LLM Invocations Counter ────────────────────────────────────────
# Tracks total LLM calls broken down by component/node.
# Helps detect which agent (Deploy vs Log vs Synthesizer) consumes the most LLM operations.
LLM_CALLS_TOTAL = Counter(
    "k8s_copilot_llm_calls_total",
    "Total number of LLM invocations executed across graph nodes.",
    ["node_name"],  # Label: "deploy_investigator", "log_investigator", "synthesizer"
)


def metrics_endpoint_response() -> Response:
    """
    Handler for GET /metrics endpoint.
    Returns current metric values in the standard Prometheus text exposition format.
    Content-Type: text/plain; version=0.0.4; charset=utf-8
    """
    data = generate_latest()
    return Response(content=data, media_type=CONTENT_TYPE_LATEST)
